### ISSUE TITLE
Unable to install via pip

### ISSUE THREAD

**Issue by jayfk** [mgrp/django-distill#4]
The packages `setup.py` imports `__version__` from `django_distill/__init__.py` which imports `url` from `django.conf.urls`.

This is problematic if Django is not installed, e.g. when using pip to install all the packages in a `requirements.txt` and pip decides to install django-distill before it is installing Django.
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pr2k64s3/django-distill/setup.py", line 6, in <module>
        from django_distill import __version__ as version
      File "/tmp/pip-build-pr2k64s3/django-distill/django_distill/__init__.py", line 4, in <module>
        from django_distill.distill import distill_url
      File "/tmp/pip-build-pr2k64s3/django-distill/django_distill/distill.py", line 4, in <module>
        from django.conf.urls import url
    ModuleNotFoundError: No module named 'django'
```

**Comment by meeb** [comment]
Ah, yes, well spotted thanks. That was rather silly. I'll push a fix for that shortly.

**Comment by meeb** [comment]
Pushed v0.7 which just removes the problem import, tested and pip install works without having Django installed first now. Cheers for finding it.

**Comment by jayfk** [comment]
Thanks 👍
